import os 
import sys
import pandas as pd

# input paths
tissue_id_path = config['tissue_id_path']
covariates_dir = config['covariates_dir']
expression_dir = config['expression_dir']
chr_list_path = config['chr_list_path']
genotype_stem = config['genotype_stem']

# output paths
filtered_expression_output_dir = config['filtered_expression_output_dir']
clusters_dir = config['clusters_dir']
eqtl_output_dir = config['eqtl_output_dir']
pcqtl_output_dir = config['pcqtl_output_dir']
pc_output_dir = config['pc_output_dir']
overlap_output_dir = config['overlap_output_dir']
annotations_output_dir = config['annotations_output_dir']

# cluster params
max_cluster_size = 50
min_cluster_size = 2
min_corr_cutoff = config['min_corr_cutoff']
percent_corr_cutoff = float(config['percent_corr_cutoff'])
cutoff_type = config['cutoff_type']


# null params
null_sizes=[2,3,4,5]

# annotation paths
gencode_path = config['gencode_path']
full_abc_path = config['full_abc_path']
abc_match_path = config['abc_match_path']
ctcf_match_path = config['ctcf_match_path']
ctcf_dir = config['ctcf_dir'] 
paralog_path = config['paralog_path']
go_path = config['go_path']
cross_map_path = config['cross_map_path']
tad_path = config['tad_path']


# load in all the wildcards
df = pd.read_csv(tissue_id_path, header=0)
tissue_ids = list(df['Tissue'])
print('Running on tissues:{}'.format(tissue_ids))

df = pd.read_csv(chr_list_path, header=0)
chr_list = list(df['chr_id'])

include: 'rules/pcqtl.smk'
include: 'rules/eqtl.smk'
include: 'rules/annotate.smk'
include: 'rules/clusters.smk'


# to remove a bloated .snakemake directory after sucessful completion
#import shutil
#onsuccess:
#    shutil.rmtree(".snakemake")

rule all:
    input:
        clusters = expand(clusters_dir + '{TISSUE}_clusters_all_chr.csv', TISSUE = tissue_ids),
        annotated_clusters = expand(annotations_output_dir + '{TISSUE}_clusters_annotated.csv', TISSUE = tissue_ids),
        annotated_nulls =  expand(annotations_output_dir + '{TISSUE}_null_{CLUSTER_SIZE}genes_annotated.csv', TISSUE = tissue_ids, CLUSTER_SIZE = null_sizes),
        vep = expand(annotations_output_dir + '{TISSUE}.v8.leadvars.vep.vcf', TISSUE = tissue_ids),
        overlap = expand(overlap_output_dir + '{TISSUE}.v8.overlap.txt', TISSUE = tissue_ids),
        pcqtl_susie = expand(pcqtl_output_dir + '{TISSUE}/{TISSUE}.v8.pcs.susie.txt', TISSUE = tissue_ids),
        pc_permutation = expand(pcqtl_output_dir + '{TISSUE}/{TISSUE}.v8.pcs.cis_independent_qtl.txt.gz', TISSUE = tissue_ids),
        pcqtl_nominal = expand(pcqtl_output_dir + '{TISSUE}/{TISSUE}.v8.pcs.cis_qtl_pairs.{CHROM}.parquet', CHROM=chr_list, TISSUE = tissue_ids),
        eqtl_susie = expand(eqtl_output_dir + '{TISSUE}/{TISSUE}.v8.cluster_genes.susie.txt', TISSUE = tissue_ids),
        eqtl_permutation = expand(eqtl_output_dir + '{TISSUE}/{TISSUE}.v8.cluster_genes.cis_independent_qtl.txt.gz', TISSUE=tissue_ids),
        eqtl_nominal = expand(eqtl_output_dir + '{TISSUE}/{TISSUE}.v8.cluster_genes.cis_qtl_pairs.{CHROM}.parquet', CHROM=chr_list, TISSUE=tissue_ids),
        # controls that are all genes, not just cluster genes
        #chr22_susie = expand('output/chr22_eqtl/{TISSUE}/{TISSUE}.v8.chr22_genes.susie.txt', TISSUE = tissue_ids),
        #control_vep = expand('output/chr22_eqtl_annotations/{TISSUE}.v8.chr22_genes.leadvars.vep.vcf', TISSUE = tissue_ids)




