# inputs

# for QTL mapping
tissue_id_path: "data/references/selected_tissue_ids.txt"
covariates_dir: "data/processed/covariates_peers/"
expression_dir: "data/processed/normalized_expression_proteincoding/"
chr_list_path: "data/references/chrs.csv"
genotype_stem: "data/processed/genotypes/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.SHAPEIT2_phased.MAF01"

# for cluster annotation
gencode_path: "data/references/gencode.v26.tss_annotated.genes.txt"
abc_path: "data/references/ABC.hg38.bed"
ctcf_match_path: "data/references/ctcf_matched_gtex.txt"
ctcf_dir: "data/references/ctcf_chip_dir"
paralog_path: "/data/references/paralogs_biomart_ensembl97.tsv.gz"
go_path: "data/references/go_biomart_ensembl97.tsv.gz"
cross_map_path: "data/references/hg38_cross_mappability_strength_symmetric_mean_sorted.txt.gz"
tad_path: "data/references/HiC_IMR90_DI_10kb.hg38.txt"

# for coloc
gwas_meta: "data/references/gwas_metadata.txt"
gtex_meta: "data/references/gtex_sample_sizes.txt"
gwas_folder: "data/references/gwas_summary_stats/"
use_susie: "True"


# outputs
filtered_expression_output_dir: "output/proteincoding_main/clusters_expression/"
clusters_dir: "output/proteincoding_main/clusters/"
eqtl_output_dir: "output/proteincoding_main/control_eqtl/"
pcqtl_output_dir: "output/proteincoding_main/pcqtl/"
pc_output_dir: "output/proteincoding_main/pcs/"
overlap_output_dir: "output/proteincoding_main/overlap/"
annotations_output_dir: "output/proteincoding_main/annotations/"
coloc_output_dir: "output/proteincoding_main/coloc/"


# params
percent_corr_cutoff: .7
cutoff_type: "pvalue"
min_corr_cutoff: 0.1 



# Working directory prefix
working_dir: "$HOME/pcqtls"
# Code directory within working direcotry
code_dir: "workflow/scripts"