# inputs

# for QTL mapping
tissue_id_path: "data/references/selected_tissue_ids.txt"
covariates_dir: "data/processed/covariates_peers/"
expression_dir: "data/processed/normalized_expression_proteincoding/"
chr_list_path: "data/references/chrs.csv"
genotype_stem: "data/processed/genotypes/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.SHAPEIT2_phased.MAF01"

# for cluster annotation
gencode_path: "data/references/gencode.v26.tss_annotated.genes.txt"
full_abc_path: "data/references/functional_annotations/ABC_predictions/ABC.hg38.bed"
abc_match_path: "data/references/functional_annotations/ABC_predictions/ABC_matched_gtex.txt"
ctcf_match_path: "data/references/functional_annotations/ctcf_chip/ctcf_matched_gtex.txt"
ctcf_dir: "data/references/functional_annotations/ctcf_chip"
paralog_path: "/data/references/functional_annotations/paralogs_biomart_ensembl97.tsv.gz"
go_path: "data/references/functional_annotations/go_biomart_ensembl97.tsv.gz"
cross_map_path: "data/references/cross_mappability/cross_mappability_100_agg.csv"
tad_path: "data/references/TAD_annotations/TADs_hg38/converted_HiC_IMR90_DI_10kb.txt"

# for coloc
gwas_meta: "data/references/gwas_metadata.txt"
gtex_meta: "data/references/gtex_sample_sizes.txt"
gwas_folder: "data/references/gwas_summary_stats/"



# outputs
filtered_expression_output_dir: "output/proteincoding_main/clusters_expression/"
clusters_dir: "output/proteincoding_main/clusters/"
eqtl_output_dir: "output/proteincoding_main/control_eqtl/"
pcqtl_output_dir: "output/proteincoding_main/pcqtl/"
pc_output_dir: "output/proteincoding_main/pcs/"
overlap_output_dir: "output/proteincoding_main/overlap/"
annotations_output_dir: "output/proteincoding_main/annotations/"
coloc_output_dir: "output/proteincoding_main/coloc/"


# params
percent_corr_cutoff: .7
cutoff_type: "pvalue"
min_corr_cutoff: 0.1 


# code
code_dir: "workflow/scripts"